os: osx
language: cpp
compiler: clang

before_install:
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew outdated pyenv || brew upgrade pyenv
  - brew outdated boost || brew upgrade boost
  - brew install swig
  - brew install lcov
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - tests/unit_tests

after_success:
  - cd ..
  - coveralls -e lib -e tests -e benchmarks -e build/CMakeFiles --gcov-options '\-lp'
